language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
  - shards
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_SHARDS_DIR=shards
  - BINARYBUILDER_AUTOMATIC_APPLE=true
  - BINARYBUILDER_USE_CCACHE=true
sudo: required
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
- julia build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: ZnVq4XFTmoPh9s3W7DEty7Hgkm8X0V3ht5REgh5OCdDMhMDCv7yjglX5D0TuY+HioiDzqhXGf7ZJo9o6NFDmLlCPWgUmeb8sEO/Bhg5CDnU9+8Dep/steBzSButJNTlNLV0eLqo8nsIM6WnEv0t3/NUS8WgfA2aRMrkPUvaQpSCb+hQI/kWxbag1xnj/66lE5idhGBj914hi7mk+JqRSI5KVxsC+STq0Zgb8b56kZ7LQFf0s4AoZy8q40W51LVacvAHCFNrkCOW93KS+mR7h/NQLJRZIRGSyRJhiwEnpF2zrqqtUtv1+FhBOkAef7euDqDLGJiM0aAv8X4L6md797Yed/tI4CHXxeUrqXIku+U+DokOyN+IB4Tl/kioFxiUJS5TLHlVEjoSon8aDxDfWZ3pary9TwF5G/8C19ZlScXWbDID87h2ObkPOogeSzNHngwms4DOLzh+gYt42a6Ryimq25uibVtudpueWly7cg+QLb17zp1A6l+dz79ZSDVvwVcxuHFLulnalB8b0AMbyuEkNpNMvAA2R+okMPpWfP3grdejn9cm58YiJ0LpYx8nNpDvC8kyNkZAYMAO7FVEuJdd51HZZC9rLmKJDrOxcspuTnEI6NCWErQqP/okWdW+WZBu48o7KRhvzOirBlLHjUndeY4AcBFJPcODpFyhPKN0=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: ianshmean/SharedMimeInfoBuilder
